version: '3'
services:
    app:
        container_name: tmk-app
        restart: always
        build: .
        ports:
            - '7000:7000'
        links:
            - mongo
    mongo:
        container_name: tmk-mongo
        image: mongo:5.0
        volumes:
            - ../mongodata:/data/db
        ports:
            - '27017:27018'
